name: 'real_estate_dbt'
version: '1.0.0'
profile: 'real_estate_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:   
  - "target"
  - "dbt_packages"

models:
  real_estate_dbt:
    bronze:
      +materialized: view
    silver:
      +materialized: view
    gold:
      +materialized: view

